version: 2
updates:

  # <https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#enabling-dependabot-version-updates-for-actions>
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
