codecov:
  require_ci_to_pass: true

comment:
    behavior: default
    branches:
        - "master"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%

    patch:
      default:
        target: 100%
