# To use:
#
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate aesara-dev
#
name: aesara-dev
channels:
  - conda-forge
  - numba
dependencies:
  - python
  - compilers
  - numpy>=1.17.0,<2.0.0
  - scipy>=0.14,<=1.12.0
  - filelock
  - etuples
  - logical-unification
  - miniKanren
  - cons
  # Intel BLAS
  - mkl
  - mkl-service
  - libblas=*=*mkl
  # numba backend
  - numba>=0.57.0,<0.58.0
  - numba-scipy
  # For testing
  - coveralls
  - diff-cover
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-benchmark
  # For building docs
  - sphinx>=1.3
  - sphinx_rtd_theme
  - pygments
  - pydot
  - ipython
  # developer tools
  - pre-commit
  - packaging
  - typing_extensions
  # optional
  - sympy
  - cython
