package:
  name: theano
  version: {{ environ.get('THEANO_VERSION') }}

source:
  path: ../

build:
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - six >=1.9.0
  run:
    - python
    - mkl-service
    - libpython >=2.0  [win]
    - m2w64-toolchain  [win]
    - six >=1.9.0
    - numpy >=1.9.1
    - scipy >=0.14.0
    - {{ pin_compatible('pygpu', '0.7', max_pin='0.8') }}   # [not osx]
    - jax  # [py>=37 and not win]

test:
  imports:
    - theano

about:
  home: http://deeplearning.net/software/theano/
  license: BSD 3-Clause
  license_family: BSD
  summary: Optimizing compiler for evaluating mathematical expressions on CPUs and GPUs.
  summary: Fork of Theano for PyMC3. An optimizing compiler for evaluating mathematical expressions on CPUs and GPUs.
  dev_url: https://github.com/pymc-devs/Theano-PyMC/
  doc_url: http://deeplearning.net/software/theano/
