package:
  name: aesara
  version: {{ environ.get('AESARA_VERSION') }}

source:
  path: ../

build:
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - mkl-service
    - libpython >=2.0  [win]
    - m2w64-toolchain  [win]
    - numpy >=1.9.1
    - scipy >=0.14.0
    - {{ pin_compatible('pygpu', '0.7', max_pin='0.8') }}   # [not osx]
    - jax  # [py>=37 and not win]
    - filelock

test:
  imports:
    - aesara

about:
  home: https://github.com/pymc-devs/aesara/
  license: BSD 3-Clause
  license_family: BSD
  summary: Optimizing compiler for evaluating mathematical expressions on CPUs and GPUs.
  summary: Fork of Aesara for PyMC3. An optimizing compiler for evaluating mathematical expressions on CPUs and GPUs.
  dev_url: https://github.com/pymc-devs/aesara/
  doc_url: https://aesara.readthedocs.io/en/latest/index.html
