name: Development builds
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build_and_publish:
    name: Build source distribution
    if: github.repository == 'aesara-devs/aesara'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies and customize pyproject.toml
        run: |
          # Download dasel to modify pyproject.toml
          curl -sSLf https://github.com/TomWright/dasel/releases/download/v2.0.2/dasel_linux_amd64 \
            -L -o /tmp/dasel && chmod +x /tmp/dasel

          /tmp/dasel put -f pyproject.toml project.name -v aesara-nightly

          # Install build prerequisites
          python -m pip install -U pip build
      - name: Build the sdist
        run: python -m build --sdist .
        env:
          BUILD_AESARA_NIGHTLY: true
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.nightly_pypi_secret }}
